### ISSUE TITLE
BSONError: cyclic dependency detected at Session#sync

### ISSUE THREAD

**Issue by memetrollsXD** [Crepe-Inc/CrepeSR#20]
This error is likely related to [Player#save](https://github.com/Crepe-Inc/CrepeSR/blob/d7e0d429064a08ac3d862c2bcd67be7fe5729960/src/server/kcp/Session.ts#L82)

Possible cause lineups?

**Comment by phuchptty** [comment]
I cause this issue because I using Mongo Atlas. I fixed it by removing `?retryWrites=true` from connect URI.

**Comment by memetrollsXD** [comment]
Fixed by #35
