### ISSUE TITLE
missing file: "start"

### ISSUE THREAD

**Issue by alyssa16** [Crepe-Inc/CrepeSR#39]
when i type in ```npm run start``` after doing ```npm install ```, it gives me missing file: "start"

**Comment by alyssa16** [comment]
C:\Users\smica\Downloads\CrepeSR>npm run start                                                                          npm ERR! Missing script: "start"                                                                                        npm ERR!                                                                                                                npm ERR! Did you mean one of these?                                                                                     npm ERR!     npm star # Mark your favorite packages                                                                     npm ERR!     npm stars # View packages marked as favorites                                                              npm ERR!                                                                                                                npm ERR! To see a list of scripts, run:                                                                                 npm ERR!   npm run                                                                                                                                                                                                                              npm ERR! A complete log of this run can be found in:                                                                    npm ERR!     C:\Users\smica\AppData\Local\npm-cache\_logs\2022-08-04T06_44_32_570Z-debug-0.log

**Comment by gawgua** [comment]
`npm start`

**Comment by alyssa16** [comment]
the error happens when i do that command

**Comment by alyssa16** [comment]
is there any fix available?

**Comment by WEDeach** [comment]
check if your `package.json` contains scripts -> start

https://github.com/Crepe-Inc/CrepeSR/blob/main/package.json#L6

**Comment by alyssa16** [comment]
i do have start in package.json

**Comment by AkaShrug** [comment]
u will also get that error if it cant find src/index.ts

**Comment by alyssa16** [comment]
it cant find start i didnt see anything abt it cant find src/index.ts

**Comment by alyssa16** [comment]
can*

**Comment by AkaShrug** [comment]
try joining the discord server and ask in support channel

**Comment by alyssa16** [comment]
i am already in it, pierro the jester#0541

**Comment by alyssa16** [comment]
they also told me to ask devs

**Comment by TheLostTree** [comment]
your npm is not working properly? reinstall

npm run start should run the script under "start" in your package.json
